# k8s/backups/postgres-backup.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:13
            env:
            - name: PGHOST
              value: "postgres"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -Fc $PGDATABASE > /backup/dump_$(date +%Y-%m-%d).pgdump
              aws s3 cp /backup/dump_$(date +%Y-%m-%d).pgdump s3://backup-bucket/
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure